# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: struct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstruct.proto\x12\x06struct\"\x98\x02\n\x06Struct\x12\x19\n\x0cstring_field\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x0b\x61rray_field\x18\x02 \x03(\t\x12=\n\x10\x64ictionary_field\x18\x03 \x03(\x0b\x32#.struct.Struct.DictionaryFieldEntry\x12\x1a\n\rinteger_field\x18\x04 \x01(\x03H\x01\x88\x01\x01\x12\x18\n\x0b\x66loat_field\x18\x05 \x01(\x01H\x02\x88\x01\x01\x1a\x36\n\x14\x44ictionaryFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0f\n\r_string_fieldB\x10\n\x0e_integer_fieldB\x0e\n\x0c_float_field\",\n\x0cRootedStruct\x12\x1c\n\x04root\x18\x06 \x01(\x0b\x32\x0e.struct.Structb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'struct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRUCT_DICTIONARYFIELDENTRY._options = None
  _STRUCT_DICTIONARYFIELDENTRY._serialized_options = b'8\001'
  _STRUCT._serialized_start=25
  _STRUCT._serialized_end=305
  _STRUCT_DICTIONARYFIELDENTRY._serialized_start=200
  _STRUCT_DICTIONARYFIELDENTRY._serialized_end=254
  _ROOTEDSTRUCT._serialized_start=307
  _ROOTEDSTRUCT._serialized_end=351
# @@protoc_insertion_point(module_scope)
